---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kanico-cm
data:
  Dockerfile: |
    FROM nginx:1.17
    LABEL maintainer="Anselme TCHASSEM"
    RUN rm -rf /usr/share/nginx/html/*
    COPY . /usr/share/nginx/html/
    EXPOSE 80
    CMD ["nginx", "-g", "daemon off;"]